### PR TITLE
Regressor

### PR DESCRIPTION
**Pull request by kenzabenjelloun**

### CODE REVIEW

**Comment by kenzabenjelloun** [comment]
Hi ! 
I am Alexandre's teammate for this AMF project ! 
I am working on the regressor, this is a first version of the code. It doesn't pass all the tests yet..
I used the same original repository as the classifier.

**Comment by smastelini** [comment]
Hi @kenzabenjelloun, I am happy to hear that there will be a regressor too! :D

After @AlexandreChaussard merges #3, I suggest pulling the latest changes to keep up to date. Do not hesitate to ask for any assistance if needed!

**Comment by AlexandreChaussard** [comment]
Sure thing, #3 is almost there !

**Comment by kenzabenjelloun** [comment]
Thank you @smastelini ! Is it ok to contact you via discord ?

**Comment by smastelini** [comment]
Of course! I am currently in contact with @AlexandreChaussard to align the PR efforts. Feel free to reach me there :)

**Pull request closed without merging**
